import { defineTheme } from 'moraine/theme'

export const themes = [
  defineTheme({ button: { base: { root: 'rounded-1' }, defaultVariants: { size: 'sm' } } }),
  defineTheme({ button: { base: { root: 'rounded-2' }, defaultVariants: { size: 'md' } } }),
  defineTheme({ button: { base: { root: 'rounded-3' }, defaultVariants: { variant: 'ghost' } } }),
  defineTheme({ button: { base: { root: 'rounded-4' }, defaultVariants: { variant: 'outline' } } }),
  defineTheme({ button: { base: { root: 'rounded-5' }, defaultVariants: { size: 'lg' } } }),
  defineTheme({ button: { base: { root: 'rounded-6' }, defaultVariants: { size: 'sm' } } }),
  defineTheme({ button: { base: { root: 'rounded-7' }, defaultVariants: { size: 'md' } } }),
  defineTheme({ button: { base: { root: 'rounded-8' }, defaultVariants: { variant: 'ghost' } } }),
  defineTheme({ button: { base: { root: 'rounded-9' }, defaultVariants: { variant: 'outline' } } }),
  defineTheme({ button: { base: { root: 'rounded-10' }, defaultVariants: { size: 'lg' } } }),
  defineTheme({ button: { base: { root: 'rounded-11' }, defaultVariants: { size: 'sm' } } }),
  defineTheme({ button: { base: { root: 'rounded-12' }, defaultVariants: { size: 'md' } } }),
  defineTheme({ button: { base: { root: 'rounded-13' }, defaultVariants: { variant: 'ghost' } } }),
  defineTheme({
    button: { base: { root: 'rounded-14' }, defaultVariants: { variant: 'outline' } },
  }),
  defineTheme({ button: { base: { root: 'rounded-15' }, defaultVariants: { size: 'lg' } } }),
  defineTheme({ button: { base: { root: 'rounded-16' }, defaultVariants: { size: 'sm' } } }),
  defineTheme({ button: { base: { root: 'rounded-17' }, defaultVariants: { size: 'md' } } }),
  defineTheme({ button: { base: { root: 'rounded-18' }, defaultVariants: { variant: 'ghost' } } }),
  defineTheme({
    button: { base: { root: 'rounded-19' }, defaultVariants: { variant: 'outline' } },
  }),
  defineTheme({ button: { base: { root: 'rounded-20' }, defaultVariants: { size: 'lg' } } }),
  defineTheme({ button: { base: { root: 'rounded-21' }, defaultVariants: { size: 'sm' } } }),
  defineTheme({ button: { base: { root: 'rounded-22' }, defaultVariants: { size: 'md' } } }),
  defineTheme({ button: { base: { root: 'rounded-23' }, defaultVariants: { variant: 'ghost' } } }),
  defineTheme({
    button: { base: { root: 'rounded-24' }, defaultVariants: { variant: 'outline' } },
  }),
  defineTheme({ button: { base: { root: 'rounded-25' }, defaultVariants: { size: 'lg' } } }),
  defineTheme({ button: { base: { root: 'rounded-26' }, defaultVariants: { size: 'sm' } } }),
  defineTheme({ button: { base: { root: 'rounded-27' }, defaultVariants: { size: 'md' } } }),
  defineTheme({ button: { base: { root: 'rounded-28' }, defaultVariants: { variant: 'ghost' } } }),
  defineTheme({
    button: { base: { root: 'rounded-29' }, defaultVariants: { variant: 'outline' } },
  }),
  defineTheme({ button: { base: { root: 'rounded-30' }, defaultVariants: { size: 'lg' } } }),
  defineTheme({ button: { base: { root: 'rounded-31' }, defaultVariants: { size: 'sm' } } }),
  defineTheme({ button: { base: { root: 'rounded-32' }, defaultVariants: { size: 'md' } } }),
  defineTheme({ button: { base: { root: 'rounded-33' }, defaultVariants: { variant: 'ghost' } } }),
  defineTheme({
    button: { base: { root: 'rounded-34' }, defaultVariants: { variant: 'outline' } },
  }),
  defineTheme({ button: { base: { root: 'rounded-35' }, defaultVariants: { size: 'lg' } } }),
  defineTheme({ button: { base: { root: 'rounded-36' }, defaultVariants: { size: 'sm' } } }),
  defineTheme({ button: { base: { root: 'rounded-37' }, defaultVariants: { size: 'md' } } }),
  defineTheme({ button: { base: { root: 'rounded-38' }, defaultVariants: { variant: 'ghost' } } }),
  defineTheme({
    button: { base: { root: 'rounded-39' }, defaultVariants: { variant: 'outline' } },
  }),
  defineTheme({ button: { base: { root: 'rounded-40' }, defaultVariants: { size: 'lg' } } }),
]
