import type { MoraineDesign, DESIGN_OPTIONS } from './types.ts'

type DesignComponents = Omit<MoraineDesign, typeof DESIGN_OPTIONS>

export const SLOT_SKELETONS = {
  accordion: [
    'root',
    'item',
    'header',
    'trigger',
    'leading',
    'label',
    'trailing',
    'content',
    'contentInner',
  ],
  avatar: ['root', 'image', 'fallback', 'fallbackIcon', 'badge'],
  avatarGroup: ['root', 'item', 'count', 'image', 'fallback', 'fallbackIcon', 'badge'],
  badge: ['root', 'leading', 'label', 'trailing'],
  breadcrumb: ['root', 'list', 'item', 'link', 'page', 'leading', 'label', 'separator'],
  button: ['root', 'loading', 'leading', 'label', 'trailing'],
  buttonGroup: ['root', 'separator'],
  card: ['root', 'header', 'title', 'description', 'action', 'body', 'footer'],
  checkbox: [
    'root',
    'control',
    'indicator',
    'icon',
    'wrapper',
    'container',
    'label',
    'description',
  ],
  checkboxGroup: [
    'root',
    'fieldset',
    'legend',
    'item',
    'container',
    'control',
    'indicator',
    'icon',
    'wrapper',
    'label',
    'description',
  ],
  collapsible: ['root', 'trigger', 'contentWrapper', 'content'],
  commandPalette: [
    'root',
    'inputWrapper',
    'input',
    'listbox',
    'footer',
    'group',
    'label',
    'item',
    'itemLeading',
    'itemWrapper',
    'itemLabel',
    'itemDescription',
    'itemTrailing',
    'search',
    'close',
    'empty',
  ],
  contextMenu: [
    'trigger',
    'overlay',
    'content',
    'group',
    'label',
    'separator',
    'item',
    'itemLeading',
    'itemWrapper',
    'itemLabel',
    'itemDescription',
    'itemTrailing',
    'itemKbds',
    'itemIndicator',
    'itemSub',
  ],
  dialog: [
    'trigger',
    'overlay',
    'content',
    'header',
    'wrapper',
    'title',
    'description',
    'close',
    'body',
    'footer',
  ],
  dropdownMenu: [
    'trigger',
    'overlay',
    'content',
    'group',
    'label',
    'separator',
    'item',
    'itemLeading',
    'itemWrapper',
    'itemLabel',
    'itemDescription',
    'itemTrailing',
    'itemKbds',
    'itemIndicator',
    'itemSub',
  ],
  fileUpload: [
    'root',
    'control',
    'wrapper',
    'icon',
    'label',
    'description',
    'files',
    'file',
    'filePreview',
    'fileMeta',
    'fileName',
    'fileSize',
    'fileRemove',
  ],
  form: ['root'],
  formField: [
    'root',
    'wrapper',
    'labelWrapper',
    'label',
    'container',
    'description',
    'error',
    'hint',
    'help',
  ],
  icon: ['root'],
  input: ['root', 'input', 'leading', 'trailing'],
  inputNumber: ['root', 'input', 'controls', 'increment', 'decrement'],
  kbd: ['root'],
  kbdGroup: ['root', 'chord', 'item', 'divider', 'sequenceDivider'],
  modal: ['overlay', 'content'],
  multiSelect: [
    'root',
    'control',
    'input',
    'leading',
    'trigger',
    'clear',
    'tagsContainer',
    'tag',
    'tagRemove',
    'tagOverflow',
    'content',
    'listbox',
    'group',
    'label',
    'item',
    'empty',
    'itemLabel',
    'itemDescription',
    'itemTrailing',
  ],
  pagination: ['root', 'list', 'item', 'link', 'prev', 'next', 'ellipsis', 'controlLabel'],
  popover: ['trigger', 'content', 'body'],
  progress: ['root', 'track', 'indicator', 'status', 'steps', 'step'],
  radioGroup: [
    'root',
    'item',
    'control',
    'container',
    'indicator',
    'wrapper',
    'label',
    'description',
  ],
  resizable: ['root', 'panel', 'divider', 'handle', 'crossTarget'],
  select: [
    'root',
    'control',
    'input',
    'leading',
    'trigger',
    'clear',
    'content',
    'listbox',
    'group',
    'label',
    'item',
    'empty',
    'itemLabel',
    'itemDescription',
    'itemTrailing',
  ],
  separator: ['root'],
  sheet: [
    'trigger',
    'overlay',
    'content',
    'header',
    'wrapper',
    'title',
    'description',
    'actions',
    'close',
    'body',
    'footer',
  ],
  sidebarFrame: [
    'root',
    'desktopLayout',
    'sidebar',
    'sidebarHeader',
    'sidebarBody',
    'sidebarFooter',
    'main',
  ],
  slider: ['root', 'track', 'range', 'divider', 'thumb'],
  stepper: [
    'root',
    'header',
    'item',
    'container',
    'trigger',
    'indicator',
    'icon',
    'separator',
    'wrapper',
    'title',
    'description',
    'content',
  ],
  switch: ['root', 'track', 'thumb', 'icon', 'wrapper', 'label', 'description'],
  tabs: ['root', 'list', 'indicator', 'trigger', 'leading', 'label', 'trailing', 'content'],
  textarea: ['root', 'header', 'input', 'footer'],
  tooltip: ['trigger', 'positioner', 'content', 'text', 'kbds', 'kbd'],
} satisfies {
  [K in keyof DesignComponents]: readonly (keyof ReturnType<DesignComponents[K]['recipe']>)[]
}
