name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - '.node-version'
      - 'package.json'
      - 'nub.jsonc'
      - 'nub.lock'
      - 'tsconfig.json'
      - 'tsdown.config.ts'
      - 'vitest.config.ts'
      - '.github/workflows/CI.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - '.node-version'
      - 'package.json'
      - 'nub.jsonc'
      - 'nub.lock'
      - 'tsconfig.json'
      - 'tsdown.config.ts'
      - 'vitest.config.ts'
      - '.github/workflows/CI.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: nubjs/setup-nub@v0
        with:
          cache: true
          cache-dependency-path: |
            package.json
            nub.lock
            nub.jsonc

      - run: nub ci

      - run: nub run qa

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: nubjs/setup-nub@v0
        with:
          cache: true
          cache-dependency-path: |
            package.json
            nub.lock
            nub.jsonc

      - run: nub ci

      - run: nub run test
